name: run main.py
on:
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours
  pull_request:
      branches:
        - main
  workflow_dispatch: # Add this to test manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ← ADD THIS!
    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5  # Updated version
        with:
            python-version: '3.x' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: execute py script 
        run: python main.py config.json
      - name: commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "updated streams $(date +'%Y-%m-%d %H:%M:%S')"
          git push
